INSERT INTO USERS (ID_PK, HASHED_PASSWORD, MOBILE, MOBILE_CONFIRMED, EMAIL, EMAIL_CONFIRMED, LEGAL,
                   FIRST_NAME, LAST_NAME, LEGAL_NAME, NATIONAL_ID, TWO_FACTOR_ENABLED, CREATED,
                   ACCESS_FAILED_COUNT, LOCK_EXPIRED, SUSPENDED, DELETED, FULL_NAME, MEDIUM)
VALUES (-1, E'jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI', '+989129999999', TRUE, E'mtyn.local@gmail.com', TRUE, FALSE,
        E'ادمین',
        E'اصلی', NULL, NULL, FALSE, '2019-08-05 11:11:06.552000', 0, NULL, FALSE, NULL, NULL, 'WEB');

INSERT INTO USER_PROFILE (ID_PK, IMAGE, PHONE, FAX, GENDER, BIRTH_DATE, REGISTRATION_NO,
                          ECONOMIC_CODE, LOCALE)
VALUES (-1, NULL, NULL, NULL, 0,null, NULL, NULL, NULL);

INSERT INTO SECURITY_ROLE (ID_PK, CATEGORY, NAME, DELETED, SHOW, TYPE)
VALUES (-1, NULL, E'ادمین اصلی', FALSE, FALSE, 0);

INSERT INTO USER_SESSION(ID_PK, AGENT, CLIENT, CREATED, FIREBASE_TOKEN, IP, OS, UNIQUE_ID, USER_ID_FK)
VALUES (-1, 'Mozilla', 'WEB', '2020-09-06 10:56:34.086', NULL, '91.92.205.199', 'Unix', '24854387502', -1);

INSERT INTO SECURITY_REST (ID_PK, HTTP_METHOD, URL)
VALUES (-1, 'GET', '/com.armin.user.admin/business/start');

INSERT INTO SECURITY_PERMISSION (ID_PK, PARENT_ID_FK, NODE_TYPE, TRAVERSAL, NAME, TYPE)
VALUES (-1, NULL, 10, TRUE, 'armin.start', 'ADMIN');

INSERT INTO SECURITY_PERMISSION_REST (PERMISSION_ID_FK, REST_ID_FK)
VALUES (-1, -1);

INSERT INTO SECURITY_REALM (ID_PK, DELETED, NAME)
VALUES (-1, FALSE, 'armin');

INSERT INTO SECURITY_USER_ROLE_REALM (ID_PK, REALM_ID_FK, ROLE_ID_FK, USER_ID_FK)
VALUES (-1, -1, -1, -1);

DELETE
FROM SECURITY_ROLE_PERMISSION
WHERE ROLE_ID_FK = -1;

INSERT INTO SECURITY_ROLE_PERMISSION(ROLE_ID_FK, PERMISSION_ID_FK)
SELECT -1, PERMISSION.ID_PK
FROM SECURITY_PERMISSION PERMISSION
WHERE PERMISSION.NODE_TYPE != 1
  AND PERMISSION.TYPE = 'ADMIN';